name: Build

on: [push, pull_request]

jobs:
  build-android-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build android-aarch64
      run: |
        chmod +x scripts/build-android-arm64.sh
        scripts/build-android-arm64.sh
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-android-aarch64
        path: android_build/lib/arm64-v8a/*.*