name: Tests

on: [push, pull_request]

jobs:

  tests-linux-amd64:

    runs-on: ubuntu-20.04

    steps:
      
    - uses: actions/checkout@v2
    
    - name: Run tests linux-amd64
      run: |
        chmod +x scripts/tests-ubuntu-amd64.sh
        scripts/tests-ubuntu-amd64.sh

